### ISSUE TITLE
Support on-prem FOSSA servers

### ISSUE THREAD

**Issue by cliffchapmanrbx** [fossa-contrib/fossa-action#143]
Hello,

We're currently using a self-hosted FOSSA instance connected to our self-hosted GitHub Enterprise server. This appears to break a number of assumptions this action makes regarding URLs and whether the GITHUB_TOKEN can be used to make API requests to github.com.

This prevents us from being able to use this action for our workflows, and we are instead defaulting to installing the raw CLI instead.

**Comment by smorimoto** [comment]
It's now supported with the latest v1 tag.
