### ISSUE TITLE
Fossa scan consistently failling with 'does not look like a targ archive'

### ISSUE THREAD

**Issue by RainbowMango** [fossa-contrib/fossa-action#239]
Hi, 

We are using this action in [our project](https://github.com/karmada-io/karmada/blob/master/.github/workflows/fossa.yml).
The scan start falling this morning. The error message:
```
Run fossa-contrib/fossa-action@v1
  with:
    fossa-api-key: 7ac0174603e25cb0a4b3ebd2e131a89f
    github-token: ***
    skip-test: true
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/8d3d65e7-5828-46dd-a445-dff3011fab86 -f /home/runner/work/_temp/44ac8ce1-36c6-423b-8311-4bbb8b49fa48
/bin/tar: This does not look like a tar archive
/bin/tar: Skipping to next header
/bin/tar: Exiting with failure status due to previous errors
Error: The process '/bin/tar' failed with exit code 2
```

You can get the whole logs from [here](https://github.com/karmada-io/karmada/runs/4197260700?check_suite_focus=true).

**Comment by smorimoto** [comment]
I understood the cause by seeing the error, I will look into it tonight. Thanks for the report!

**Comment by MomoLangenstein** [comment]
My repos have also been hit by this issue this morning - thanks for looking into it!

**Comment by smorimoto** [comment]
It's fixed with the latest v1 tag. Kick the rebuild!

**Comment by shadycuz** [comment]
Always search first ;)

**Comment by MomoLangenstein** [comment]
> 
> 
> It's now fixed with the latest v1 tag. Kick the rebuild!

Thank you very much for the very quick fix!
