### ISSUE TITLE
Action fails on pull requests

### ISSUE THREAD

**Issue by yooksi** [fossa-contrib/fossa-action#96]
When running on `master` branch the action passes:
https://github.com/real-coco-labs/pz-zdoc/runs/1930944064

When running on a pull request the action fails:
https://github.com/real-coco-labs/pz-zdoc/runs/1930929259

```
FATAL Could not initialize 
TROUBLESHOOTING: A FOSSA API key is needed to run this command.


Running `fossa analyze` performs a dependency analysis and uploads the result
to FOSSA. To run an analysis without uploading results, run:

    fossa analyze --output

You can provide your API key by setting the $FOSSA_API_KEY environment
variable. For example, try running:

    FOSSA_API_KEY=<YOUR_API_KEY_HERE> $command

You can create an API key for your FOSSA account at:
    
    app.fossa.com/account/settings/integrations/api_tokens
```

**Comment by yooksi** [comment]
When pull request was merged the action passed:
https://github.com/real-coco-labs/pz-zdoc/runs/1930986238

**Comment by smorimoto** [comment]
Are these probably the causes?
https://securitylab.github.com/research/github-actions-preventing-pwn-requests
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target

**Comment by smorimoto** [comment]
Oh disregard that.

**Comment by smorimoto** [comment]
Somehow it appears that no secret was passed in the workflow run.

**Comment by yooksi** [comment]
I am thinking the same, however it's even more perplexing that the workflow passes once it gets merged in `master`.

**Comment by smorimoto** [comment]
It seems that PR from the fork always has this problem. ​Probably the current solution is to use `pull_request_target`.

**Comment by smorimoto** [comment]
I just opened this and let me check how it works after merged it. https://github.com/real-coco-labs/pz-zdoc/pull/60

**Comment by smorimoto** [comment]
The problem with this is that if someone included the following code in workflow, it would be easily passed to a malicious user:

```
echo ${{ secrets.FOSSA_API_KEY }}

**Comment by smorimoto** [comment]
Oh, no, we can use this for open-source projects.
https://docs.fossa.com/docs/api-reference

**Comment by yooksi** [comment]
Don't think I follow, I am already using a `read-only` token.

**Comment by smorimoto** [comment]
I've added a simple document about that, and it's not possible to use the "secrets" on the pull request event, and FOSSA has implemented a push-only API key to deal with that. In fact, such constraints exist with all other CI providers.
https://github.com/fossa-contrib/fossa-action#push-only-api-token

**Comment by smorimoto** [comment]
Now if users seem to be using them together, a warning will be printed: https://github.com/fossa-contrib/fossa-action/commit/3fcdbcda80d1338bd0d882d930c50354e6d541fe

**Comment by yooksi** [comment]
Thank you, I have exposed the key in https://github.com/real-coco-labs/pz-zdoc/commit/4ca1caa91d90d62de1f41ec4a6ad67befe1e2ce4 and will see if that works when I merge with `master`.

**Comment by smorimoto** [comment]
Sounds good. Thanks for reporting this.

**Comment by yooksi** [comment]
Everything [checks out](https://github.com/real-coco-labs/pz-zdoc/pull/63/checks?check_run_id=1932472410), thanks again for helping out.

**Comment by smorimoto** [comment]
Excellent :)
